SELECT a.sid,
a.n_1,
a.p_id,
a.age,
a.data_exam,
a.height_y,
a.weight_y,
a.waist_y,
a.systolic_y,
a.diastolic_y,
a.heartbeat_y,
a.Glucose_AC_y,
a.Triglyceride_y,
a.HDL_C_y,
a.WBCb,
a.RBCb,
a.Hemoglobin,
a.Hematocrit,
a.MCV,
a.MCH,
a.MCHC,
a.RDW,
a.Platelets,
a.Transferrin,
a.Ferritin,
a.Folate,
a.AST_GOT,
a.ALT_GPT,
a.ALK_P,
a.Total_Bilirubin,
a.D_Bilirubin,
a.gamgt,
a.AFP,
a.Insulin,
a.T_Cholesterol,
ROUND(a.LDL_C_direct,0) AS LDL_C_direct,
a.VLDL_C,
a.Non_HDL_C,
a.T_CHOL_HDL_C,
a.LDL_C_HDL_C,
ROUND(a.HS_CRP,2) AS HS_CRP,
a.BUN,
a.Creatinine,
a.Estimated_GFR_x,
a.sodium,
a.K,
a.Cl,
a.CO2,
a.Calcium,
a.Inorganic_P,
a.Albumin,
a.Total_Protein,
a.Hb_A1c,
a.Estimated_AG,
a.Intact_PTH,
a.Uric_Acid,
a.HBsAg_x,
a.RPR,
a.RF,
a.H_PYAB_x,
a.Anti_HCV_x,
a.Color,
a.Turbidity,
ROUND(a.SP_Gravity,2) AS SP_Gravity,
a.pH,
a.Leukocyte,
a.Nitrite,
a.Protein,
a.Glucose,
a.Ketone,
a.Urobilinogen,
a.Bilirubin,
a.octBlood,
a.RBCu,
a.WBCu,
a.Squamus_Epi,
a.UreaNU,
a.MicroALB_U,
a.Creatinine_U,
a.TP_U,
a.Alb_Cre_ratio,
ROUND(a.TP_U_Cre_ratio,2) AS TP_U_Cre_ratio,
ROUND(a.HOMA_IR,2) AS HOMA_IR, 
a.Insulin_GLU,
a.Adiponectin,
a.Leptin,
a.TNF_A,
a.TotalVitaminD,
a.Vitamin_B12,
a.Lymphocyte,
a.Monocyte,
a.Eosinophil,
a.Basophil,
a.year_come,
a.RAND36_PF,
a.RAND36_RP,
a.RAND36_BP,
a.RAND36_GH,
a.RAND36_EF,
a.RAND36_SF,
a.RAND36_RE,
a.RAND36_EWB,
a.bmi,
a.w,
a.hyper,
a.fg,
a.HDL,
a.trig,
a.mst,
a.ms2,
a.Dysrhythmia,
ROUND(175*IF(a.sex=0, POWER(a.age,-0.203)*0.742,POWER(a.age,-0.203)*1),2) AS labage,
a.egfrn,
a.CKD_determine,
0 AS ckdstage,
IF(Alb_Cre_ratio>=30,1,0) AS ckdacr,
IF(TP_U_Cre_ratio>=150,1,0) AS ckdpcr,
IF(Alb_Cre_ratio>=30 OR TP_U_Cre_ratio>=150,1,0) AS ckdp,
b.location,
b.location2,
a.HBV_,
a.HCV_,
a.DM_determine,
0 AS pid_examdate,
a.Segment
FROM CMRC_DB_kaonthu.new_CMRC_db_testing_question_scalebigtable_20220303 AS a
INNER JOIN kao_practice_3.CMRC_all_persontimes_last_kaonthu AS b
ON a.sid = b.P_dn
