CREATE TABLE kao_practice_6.CMRC_20211013_20211225_Q (
`流水號` varchar(25) DEFAULT NULL,
`Page1` varchar(25) DEFAULT NULL,
`血型ABO` varchar(25) DEFAULT NULL,
`血型Rh` varchar(25) DEFAULT NULL,
`飲食習慣` varchar(25) DEFAULT NULL,
`飲食習慣其他` varchar(25) DEFAULT NULL,
`教育程度` varchar(25) DEFAULT NULL,
`行業` varchar(25) DEFAULT NULL,
`其他行業` varchar(25) DEFAULT NULL,
`從事時間幾年` varchar(25) DEFAULT NULL,
`工作類型` varchar(25) DEFAULT NULL,
`仍在工作` varchar(25) DEFAULT NULL,
`已退休幾年` varchar(25) DEFAULT NULL,
`宗教信仰` varchar(25) DEFAULT NULL,
`其他宗教` varchar(25) DEFAULT NULL,
`親生父親氏族` varchar(25) DEFAULT NULL,
`外省籍什麼省1` varchar(25) DEFAULT NULL,
`其他族1` varchar(25) DEFAULT NULL,
`親生母親氏族` varchar(25) DEFAULT NULL,
`外省籍什麼省2` varchar(25) DEFAULT NULL,
`其他族2` varchar(25) DEFAULT NULL,
`婚姻狀況` varchar(25) DEFAULT NULL,
`結婚年數` varchar(25) DEFAULT NULL,
`生育子女數` varchar(25) DEFAULT NULL,
`Page2` varchar(25) DEFAULT NULL,
`居住成員獨居` varchar(25) DEFAULT NULL,
`居住成員父母公婆` varchar(25) DEFAULT NULL,
`居住成員配偶` varchar(25) DEFAULT NULL,
`居住成員兄弟姊妹` varchar(25) DEFAULT NULL,
`居住成員子女` varchar(25) DEFAULT NULL,
`子女共幾人` varchar(25) DEFAULT NULL,
`居住成員女婿媳婦` varchar(25) DEFAULT NULL,
`居住成員孫子女` varchar(25) DEFAULT NULL,
`孫子共幾人` varchar(25) DEFAULT NULL,
`居住成員其他` varchar(25) DEFAULT NULL,
`其他居住成員` varchar(25) DEFAULT NULL,
`從您出生到現在曾居住過最久的地方為什麼縣市` varchar(25) DEFAULT NULL,
`從您出生到現在曾居住過最久的地方為什麼區鄉鎮市` varchar(25) DEFAULT NULL,
`承上從民國幾年` varchar(25) DEFAULT NULL,
`至民國幾年` varchar(25) DEFAULT NULL,
`自我照護` varchar(25) DEFAULT NULL,
`誰照顧你自理` varchar(25) DEFAULT NULL,
`誰照顧你父母公婆` varchar(25) DEFAULT NULL,
`誰照顧你配偶` varchar(25) DEFAULT NULL,
`誰照顧你兄弟姊妹` varchar(25) DEFAULT NULL,
`誰照顧你子女` varchar(25) DEFAULT NULL,
`誰照顧你女婿媳婦` varchar(25) DEFAULT NULL,
`誰照顧你看護` varchar(25) DEFAULT NULL,
`誰照顧你其他` varchar(25) DEFAULT NULL,
`其他照顧你的人` varchar(25) DEFAULT NULL,
`經濟來源自己` varchar(25) DEFAULT NULL,
`經濟來源父母公婆` varchar(25) DEFAULT NULL,
`經濟來源配偶` varchar(25) DEFAULT NULL,
`經濟來源兄弟姊妹` varchar(25) DEFAULT NULL,
`經濟來源子女` varchar(25) DEFAULT NULL,
`經濟來源女婿媳婦` varchar(25) DEFAULT NULL,
`經濟來源政府` varchar(25) DEFAULT NULL,
`經濟來源朋友` varchar(25) DEFAULT NULL,
`經濟來源其他` varchar(25) DEFAULT NULL,
`其他經濟來源` varchar(25) DEFAULT NULL,
`保險狀況` varchar(25) DEFAULT NULL,
`什麼保險` varchar(25) DEFAULT NULL,
`其他篩檢` varchar(25) DEFAULT NULL,
`參加其他篩檢名稱` varchar(25) DEFAULT NULL,
`篩檢關聯性` varchar(25) DEFAULT NULL,
`有親一同參加篩檢稱謂` varchar(25) DEFAULT NULL,
`有親一同參加篩檢姓名` varchar(25) DEFAULT NULL,
`Page3` varchar(25) DEFAULT NULL,
`您曾經抽過菸嗎` varchar(25) DEFAULT NULL,
`幾歲開始抽菸` varchar(25) DEFAULT NULL,
`您抽菸抽幾年` varchar(25) DEFAULT NULL,
`您是否曾戒過菸` varchar(25) DEFAULT NULL,
`已戒菸幾年未再抽` varchar(25) DEFAULT NULL,
`戒過幾年現在又抽` varchar(25) DEFAULT NULL,
`您抽菸的頻率` varchar(25) DEFAULT NULL,
`您有抽菸的日子一天可以吸多少根菸` varchar(25) DEFAULT NULL,
`您最近這一星期在家裡或工作地點有人抽煙或聞到菸味的頻率` varchar(25) DEFAULT NULL,
`您有喝茶的習慣嗎` varchar(25) DEFAULT NULL,
`您主要喝哪一種茶` varchar(25) DEFAULT NULL,
`混和以什麼茶為主` varchar(25) DEFAULT NULL,
`您喝茶喝幾年` varchar(25) DEFAULT NULL,
`您是否曾停止喝茶習慣超過6個月未喝` varchar(25) DEFAULT NULL,
`您喝茶的頻率` varchar(25) DEFAULT NULL,
`您有喝茶的日子一天可以喝多少CC的茶` varchar(25) DEFAULT NULL,
`Page4` varchar(25) DEFAULT NULL,
`您有喝咖啡的習慣嗎` varchar(25) DEFAULT NULL,
`您主要喝哪一種咖啡` varchar(25) DEFAULT NULL,
`您喝咖啡喝幾年` varchar(25) DEFAULT NULL,
`您是否曾停止喝咖啡習慣超過6個月未喝` varchar(25) DEFAULT NULL,
`您喝咖啡的頻率` varchar(25) DEFAULT NULL,
`您有喝咖啡的日子一天可以喝多少CC的咖啡` varchar(25) DEFAULT NULL,
`您曾經嚼過檳榔嗎` varchar(25) DEFAULT NULL,
`幾歲開始嚼檳榔` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔加荖藤` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔加荖葉` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔紅灰` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔白灰` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔菁仔` varchar(25) DEFAULT NULL,
`您主要嚼哪一類檳榔其他` varchar(25) DEFAULT NULL,
`其他種類檳榔` varchar(25) DEFAULT NULL,
`您嚼檳榔嚼幾年` varchar(25) DEFAULT NULL,
`您是否曾停止嚼檳榔習慣超過6個月未嚼` varchar(25) DEFAULT NULL,
`您嚼檳榔的平均頻率` varchar(25) DEFAULT NULL,
`您有嚼檳榔的日子一天可以嚼幾顆檳榔` varchar(25) DEFAULT NULL,
`Page5` varchar(25) DEFAULT NULL,
`自己有無高血壓` varchar(25) DEFAULT NULL,
`自己有無心律不整` varchar(25) DEFAULT NULL,
`自己有無心絞痛` varchar(25) DEFAULT NULL,
`自己有無心肌梗塞` varchar(25) DEFAULT NULL,
`自己有無高血脂` varchar(25) DEFAULT NULL,
`自己有無心臟衰竭` varchar(25) DEFAULT NULL,
`自己有無糖尿病` varchar(25) DEFAULT NULL,
`自己有無甲狀腺疾病` varchar(25) DEFAULT NULL,
`自己有無胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`自己有無B肝` varchar(25) DEFAULT NULL,
`自己有無C肝` varchar(25) DEFAULT NULL,
`自己有無脂肪肝` varchar(25) DEFAULT NULL,
`自己有無肝纖維化` varchar(25) DEFAULT NULL,
`自己有無肝硬化` varchar(25) DEFAULT NULL,
`自己有無大腸瘜肉` varchar(25) DEFAULT NULL,
`自己有無腸躁症` varchar(25) DEFAULT NULL,
`自己有無氣喘` varchar(25) DEFAULT NULL,
`自己有無呼吸中止` varchar(25) DEFAULT NULL,
`自己有無慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`自己有無貧血` varchar(25) DEFAULT NULL,
`自己有無血友病` varchar(25) DEFAULT NULL,
`親生父親有無高血壓` varchar(25) DEFAULT NULL,
`親生父親有無心律不整` varchar(25) DEFAULT NULL,
`親生父親有無心絞痛` varchar(25) DEFAULT NULL,
`親生父親有無心肌梗塞` varchar(25) DEFAULT NULL,
`親生父親有無高血脂` varchar(25) DEFAULT NULL,
`親生父親有無心臟衰竭` varchar(25) DEFAULT NULL,
`親生父親有無糖尿病` varchar(25) DEFAULT NULL,
`親生父親有無甲狀腺疾病` varchar(25) DEFAULT NULL,
`親生父親有無胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`親生父親有無B肝` varchar(25) DEFAULT NULL,
`親生父親有無C肝` varchar(25) DEFAULT NULL,
`親生父親有無脂肪肝` varchar(25) DEFAULT NULL,
`親生父親有無肝纖維化` varchar(25) DEFAULT NULL,
`親生父親有無肝硬化` varchar(25) DEFAULT NULL,
`親生父親有無大腸瘜肉` varchar(25) DEFAULT NULL,
`親生父親有無腸躁症` varchar(25) DEFAULT NULL,
`親生父親有無氣喘` varchar(25) DEFAULT NULL,
`親生父親有無呼吸中止` varchar(25) DEFAULT NULL,
`親生父親有無慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`親生父親有無貧血` varchar(25) DEFAULT NULL,
`親生父親有無血友病` varchar(25) DEFAULT NULL,
`親生母親有無高血壓` varchar(25) DEFAULT NULL,
`親生母親有無心律不整` varchar(25) DEFAULT NULL,
`親生母親有無心絞痛` varchar(25) DEFAULT NULL,
`親生母親有無心肌梗塞` varchar(25) DEFAULT NULL,
`親生母親有無高血脂` varchar(25) DEFAULT NULL,
`親生母親有無心臟衰竭` varchar(25) DEFAULT NULL,
`親生母親有無糖尿病` varchar(25) DEFAULT NULL,
`親生母親有無甲狀腺疾病` varchar(25) DEFAULT NULL,
`親生母親有無胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`親生母親有無B肝` varchar(25) DEFAULT NULL,
`親生母親有無C肝` varchar(25) DEFAULT NULL,
`親生母親有無脂肪肝` varchar(25) DEFAULT NULL,
`親生母親有無肝纖維化` varchar(25) DEFAULT NULL,
`親生母親有無肝硬化` varchar(25) DEFAULT NULL,
`親生母親有無大腸瘜肉` varchar(25) DEFAULT NULL,
`親生母親有無腸躁症` varchar(25) DEFAULT NULL,
`親生母親有無氣喘` varchar(25) DEFAULT NULL,
`親生母親有無呼吸中止` varchar(25) DEFAULT NULL,
`親生母親有無慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`親生母親有無貧血` varchar(25) DEFAULT NULL,
`親生母親有無血友病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無高血壓` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患高血壓` varchar(25) DEFAULT NULL,
`兄弟姊妹有無心律不整` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患心律不整` varchar(25) DEFAULT NULL,
`兄弟姊妹有無心絞痛` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患心絞痛` varchar(25) DEFAULT NULL,
`兄弟姊妹有無心肌梗塞` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患心肌梗塞` varchar(25) DEFAULT NULL,
`兄弟姊妹有無高血脂` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患高血脂` varchar(25) DEFAULT NULL,
`兄弟姊妹有無心臟衰竭` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患心臟衰竭` varchar(25) DEFAULT NULL,
`兄弟姊妹有無糖尿病` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患糖尿病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無甲狀腺疾病` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患甲狀腺疾病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`兄弟姊妹有無B肝` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患B肝` varchar(25) DEFAULT NULL,
`兄弟姊妹有無C肝` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患C肝` varchar(25) DEFAULT NULL,
`兄弟姊妹有無脂肪肝` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患脂肪肝` varchar(25) DEFAULT NULL,
`兄弟姊妹有無肝纖維化` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患肝纖維化` varchar(25) DEFAULT NULL,
`兄弟姊妹有無肝硬化` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患肝硬化` varchar(25) DEFAULT NULL,
`兄弟姊妹有無大腸瘜肉` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患大腸瘜肉` varchar(25) DEFAULT NULL,
`兄弟姊妹有無腸躁症` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患腸躁症` varchar(25) DEFAULT NULL,
`兄弟姊妹有無氣喘` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患氣喘` varchar(25) DEFAULT NULL,
`兄弟姊妹有無呼吸中止` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患呼吸中止` varchar(25) DEFAULT NULL,
`兄弟姊妹有無慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無貧血` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患貧血` varchar(25) DEFAULT NULL,
`兄弟姊妹有無血友病` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患血友病` varchar(25) DEFAULT NULL,
`子女有無高血壓` varchar(25) DEFAULT NULL,
`子女有無心律不整` varchar(25) DEFAULT NULL,
`子女有無心絞痛` varchar(25) DEFAULT NULL,
`子女有無心肌梗塞` varchar(25) DEFAULT NULL,
`子女有無高血脂` varchar(25) DEFAULT NULL,
`子女有無心臟衰竭` varchar(25) DEFAULT NULL,
`子女有無糖尿病` varchar(25) DEFAULT NULL,
`子女有無甲狀腺疾病` varchar(25) DEFAULT NULL,
`子女有無胃或十二指腸潰瘍` varchar(25) DEFAULT NULL,
`子女有無B肝` varchar(25) DEFAULT NULL,
`子女有無C肝` varchar(25) DEFAULT NULL,
`子女有無脂肪肝` varchar(25) DEFAULT NULL,
`子女有無肝纖維化` varchar(25) DEFAULT NULL,
`子女有無肝硬化` varchar(25) DEFAULT NULL,
`子女有無大腸瘜肉` varchar(25) DEFAULT NULL,
`子女有無腸躁症` varchar(25) DEFAULT NULL,
`子女有無氣喘` varchar(25) DEFAULT NULL,
`子女有無呼吸中止` varchar(25) DEFAULT NULL,
`子女有無慢性阻塞性肺病` varchar(25) DEFAULT NULL,
`子女有無貧血` varchar(25) DEFAULT NULL,
`子女有無血友病` varchar(25) DEFAULT NULL,
`Page6` varchar(25) DEFAULT NULL,
`自己有無腦中風` varchar(25) DEFAULT NULL,
`自己有無腦出血` varchar(25) DEFAULT NULL,
`自己有無腦外傷開刀` varchar(25) DEFAULT NULL,
`自己有無癲癇` varchar(25) DEFAULT NULL,
`自己有無巴金森氏症` varchar(25) DEFAULT NULL,
`自己有無失智` varchar(25) DEFAULT NULL,
`自己有無舞蹈症` varchar(25) DEFAULT NULL,
`自己有無憂鬱症` varchar(25) DEFAULT NULL,
`自己憂鬱症有過醫師診斷` varchar(25) DEFAULT NULL,
`自己有無其他精神科疾病` varchar(25) DEFAULT NULL,
`自己有無慢性腎病` varchar(25) DEFAULT NULL,
`自己有無洗腎` varchar(25) DEFAULT NULL,
`自己有無結石` varchar(25) DEFAULT NULL,
`自己有無攝護腺肥大` varchar(25) DEFAULT NULL,
`自己有無白內障` varchar(25) DEFAULT NULL,
`自己有無青光眼` varchar(25) DEFAULT NULL,
`自己有無視網膜病變` varchar(25) DEFAULT NULL,
`自己有無乾眼症` varchar(25) DEFAULT NULL,
`自己有無肺癌` varchar(25) DEFAULT NULL,
`自己有無乳癌` varchar(25) DEFAULT NULL,
`自己有無大腸癌` varchar(25) DEFAULT NULL,
`自己有無胃癌` varchar(25) DEFAULT NULL,
`自己有無肝癌` varchar(25) DEFAULT NULL,
`自己有無其他癌症` varchar(25) DEFAULT NULL,
`親生父親有無腦中風` varchar(25) DEFAULT NULL,
`親生父親有無腦出血` varchar(25) DEFAULT NULL,
`親生父親有無腦外傷開刀` varchar(25) DEFAULT NULL,
`親生父親有無癲癇` varchar(25) DEFAULT NULL,
`親生父親有無巴金森氏症` varchar(25) DEFAULT NULL,
`親生父親有無失智` varchar(25) DEFAULT NULL,
`親生父親有無舞蹈症` varchar(25) DEFAULT NULL,
`親生父親有無憂鬱症` varchar(25) DEFAULT NULL,
`親生父親憂鬱症有過醫師診斷` varchar(25) DEFAULT NULL,
`親生父親有無其他精神科疾病` varchar(25) DEFAULT NULL,
`親生父親有無慢性腎病` varchar(25) DEFAULT NULL,
`親生父親有無洗腎` varchar(25) DEFAULT NULL,
`親生父親有無結石` varchar(25) DEFAULT NULL,
`親生父親有無攝護腺肥大` varchar(25) DEFAULT NULL,
`親生父親有無白內障` varchar(25) DEFAULT NULL,
`親生父親有無青光眼` varchar(25) DEFAULT NULL,
`親生父親有無視網膜病變` varchar(25) DEFAULT NULL,
`親生父親有無乾眼症` varchar(25) DEFAULT NULL,
`親生父親有無肺癌` varchar(25) DEFAULT NULL,
`親生父親有無乳癌` varchar(25) DEFAULT NULL,
`親生父親有無大腸癌` varchar(25) DEFAULT NULL,
`親生父親有無胃癌` varchar(25) DEFAULT NULL,
`親生父親有無肝癌` varchar(25) DEFAULT NULL,
`親生父親有無其他癌症` varchar(25) DEFAULT NULL,
`親生母親有無腦中風` varchar(25) DEFAULT NULL,
`親生母親有無腦出血` varchar(25) DEFAULT NULL,
`親生母親有無腦外傷開刀` varchar(25) DEFAULT NULL,
`親生母親有無癲癇` varchar(25) DEFAULT NULL,
`親生母親有無巴金森氏症` varchar(25) DEFAULT NULL,
`親生母親有無失智` varchar(25) DEFAULT NULL,
`親生母親有無舞蹈症` varchar(25) DEFAULT NULL,
`親生母親有無憂鬱症` varchar(25) DEFAULT NULL,
`親生母親憂鬱症有過醫師診斷` varchar(25) DEFAULT NULL,
`親生母親有無其他精神科疾病` varchar(25) DEFAULT NULL,
`親生母親有無慢性腎病` varchar(25) DEFAULT NULL,
`親生母親有無洗腎` varchar(25) DEFAULT NULL,
`親生母親有無結石` varchar(25) DEFAULT NULL,
`親生母親有無攝護腺肥大` varchar(25) DEFAULT NULL,
`親生母親有無白內障` varchar(25) DEFAULT NULL,
`親生母親有無青光眼` varchar(25) DEFAULT NULL,
`親生母親有無視網膜病變` varchar(25) DEFAULT NULL,
`親生母親有無乾眼症` varchar(25) DEFAULT NULL,
`親生母親有無肺癌` varchar(25) DEFAULT NULL,
`親生母親有無乳癌` varchar(25) DEFAULT NULL,
`親生母親有無大腸癌` varchar(25) DEFAULT NULL,
`親生母親有無胃癌` varchar(25) DEFAULT NULL,
`親生母親有無肝癌` varchar(25) DEFAULT NULL,
`親生母親有無其他癌症` varchar(25) DEFAULT NULL,
`兄弟姊妹有無腦中風` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患腦中風` varchar(25) DEFAULT NULL,
`兄弟姊妹有無腦出血` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患腦出血` varchar(25) DEFAULT NULL,
`兄弟姊妹有無腦外傷開刀` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患腦外傷開刀` varchar(25) DEFAULT NULL,
`兄弟姊妹有無癲癇` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患癲癇` varchar(25) DEFAULT NULL,
`兄弟姊妹有無巴金森氏症` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患巴金森氏症` varchar(25) DEFAULT NULL,
`兄弟姊妹有無失智` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患失智` varchar(25) DEFAULT NULL,
`兄弟姊妹有無舞蹈症` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患舞蹈症` varchar(25) DEFAULT NULL,
`兄弟姊妹有無憂鬱症` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患憂鬱症` varchar(25) DEFAULT NULL,
`兄弟妹憂鬱症有過醫師診斷` varchar(25) DEFAULT NULL,
`兄弟姊妹有無其他精神科疾病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無慢性腎病` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患慢性腎病` varchar(25) DEFAULT NULL,
`兄弟姊妹有無洗腎` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患洗腎` varchar(25) DEFAULT NULL,
`兄弟姊妹有無結石` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患結石` varchar(25) DEFAULT NULL,
`兄弟姊妹有無攝護腺肥大` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患攝護腺肥大` varchar(25) DEFAULT NULL,
`兄弟姊妹有無白內障` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患白內障` varchar(25) DEFAULT NULL,
`兄弟姊妹有無青光眼` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患青光眼` varchar(25) DEFAULT NULL,
`兄弟姊妹有無視網膜病變` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患視網膜病變` varchar(25) DEFAULT NULL,
`兄弟姊妹有無乾眼症` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患乾眼症` varchar(25) DEFAULT NULL,
`兄弟姊妹有無肺癌` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患肺癌` varchar(25) DEFAULT NULL,
`兄弟姊妹有無乳癌` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患乳癌` varchar(25) DEFAULT NULL,
`兄弟姊妹有無大腸癌` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患大腸癌` varchar(25) DEFAULT NULL,
`兄弟姊妹有無胃癌` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患胃癌` varchar(25) DEFAULT NULL,
`兄弟姊妹有無肝癌` varchar(25) DEFAULT NULL,
`兄弟姊妹誰患肝癌` varchar(25) DEFAULT NULL,
`兄弟姊妹有無其他癌症` varchar(25) DEFAULT NULL,
`子女有無腦中風` varchar(25) DEFAULT NULL,
`子女有無腦出血` varchar(25) DEFAULT NULL,
`子女有無腦外傷開刀` varchar(25) DEFAULT NULL,
`子女有無癲癇` varchar(25) DEFAULT NULL,
`子女有無巴金森氏症` varchar(25) DEFAULT NULL,
`子女有無失智` varchar(25) DEFAULT NULL,
`子女有無舞蹈症` varchar(25) DEFAULT NULL,
`子女有無憂鬱症` varchar(25) DEFAULT NULL,
`子女憂鬱症有過醫師診斷` varchar(25) DEFAULT NULL,
`子女有無其他精神科疾病` varchar(25) DEFAULT NULL,
`子女有無慢性腎病` varchar(25) DEFAULT NULL,
`子女有無洗腎` varchar(25) DEFAULT NULL,
`子女有無結石` varchar(25) DEFAULT NULL,
`子女有無攝護腺肥大` varchar(25) DEFAULT NULL,
`子女有無白內障` varchar(25) DEFAULT NULL,
`子女有無青光眼` varchar(25) DEFAULT NULL,
`子女有無視網膜病變` varchar(25) DEFAULT NULL,
`子女有無乾眼症` varchar(25) DEFAULT NULL,
`子女有無肺癌` varchar(25) DEFAULT NULL,
`子女有無乳癌` varchar(25) DEFAULT NULL,
`子女有無大腸癌` varchar(25) DEFAULT NULL,
`子女有無胃癌` varchar(25) DEFAULT NULL,
`子女有無肝癌` varchar(25) DEFAULT NULL,
`子女有無其他癌症` varchar(25) DEFAULT NULL,
`Page7` varchar(25) DEFAULT NULL,
`自己無以上病史` varchar(25) DEFAULT NULL,
`自己不知道` varchar(25) DEFAULT NULL,
`自己其他未列出疾病` varchar(25) DEFAULT NULL,
`親生父親無以上病史` varchar(25) DEFAULT NULL,
`親生父親不知道` varchar(25) DEFAULT NULL,
`親生父親其他未列出疾病` varchar(25) DEFAULT NULL,
`親生母親無以上病史` varchar(25) DEFAULT NULL,
`親生母親不知道` varchar(25) DEFAULT NULL,
`親生母親其他未列出疾病` varchar(25) DEFAULT NULL,
`兄弟姊妹無以上病史` varchar(25) DEFAULT NULL,
`兄弟姊妹不知道` varchar(25) DEFAULT NULL,
`兄弟姊妹其他未列出疾病` varchar(25) DEFAULT NULL,
`子女無以上病史` varchar(25) DEFAULT NULL,
`子女不知道` varchar(25) DEFAULT NULL,
`子女其他未列出疾病` varchar(25) DEFAULT NULL,
`您是否常服用咳嗽糖漿` varchar(25) DEFAULT NULL,
`您是否常服用安眠藥` varchar(25) DEFAULT NULL,
`您是否常服用止痛抗發炎類藥物包括針劑` varchar(25) DEFAULT NULL,
`您是否正在服用高血壓藥物包括針劑` varchar(25) DEFAULT NULL,
`您是否正在服用糖尿病藥物包括針劑` varchar(25) DEFAULT NULL,
`您是否正在服用賀爾蒙藥物包括針劑` varchar(25) DEFAULT NULL,
`您是否正在服用降血脂藥物包括針劑` varchar(25) DEFAULT NULL,
`請問您最近兩星期是否有吃胃藥` varchar(25) DEFAULT NULL,
`您是否有吃中草藥的習慣非藥酒` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣否` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣維他命` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣維骨力或葡萄糖胺` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣魚肝油` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣鈣片` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣人蔘` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣靈芝` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣雞精` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣蜆精` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣提神飲料` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣葉黃素` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣膠原蛋白` varchar(25) DEFAULT NULL,
`請問您是否有吃下列食品的習慣其他` varchar(25) DEFAULT NULL,
`其他食品` varchar(25) DEFAULT NULL,
`Page8` varchar(25) DEFAULT NULL,
`您常使用塑膠袋盛裝熱食` varchar(25) DEFAULT NULL,
`您常使用塑膠餐具` varchar(25) DEFAULT NULL,
`您常吃有包裝的加工食品` varchar(25) DEFAULT NULL,
`您家中常使用保鮮膜進行微波蒸煮或包裝油性食物嗎` varchar(25) DEFAULT NULL,
`您常喝市售的塑膠杯裝的飲料` varchar(25) DEFAULT NULL,
`您常使用有香氣的衛浴用品嗎` varchar(25) DEFAULT NULL,
`您家中使用塑膠地墊嗎` varchar(25) DEFAULT NULL,
`請問您是否曾經中風` varchar(25) DEFAULT NULL,
`請問您是否曾因跌倒車禍或外力傷害撞擊到頭部` varchar(25) DEFAULT NULL,
`若曾經有過上述1或2的情形請問您當時是否意識清醒` varchar(25) DEFAULT NULL,
`Page9` varchar(25) DEFAULT NULL,
`一般來說您認為您目前的健康狀況是` varchar(25) DEFAULT NULL,
`和一年前比較您認為您目前的健康狀況是` varchar(25) DEFAULT NULL,
`費力活動跑步提重物參與劇烈運動` varchar(25) DEFAULT NULL,
`中等程度活動搬桌子拖地或打太極拳` varchar(25) DEFAULT NULL,
`提起或攜帶食品雜貨` varchar(25) DEFAULT NULL,
`爬數層樓樓梯` varchar(25) DEFAULT NULL,
`爬一層樓樓梯` varchar(25) DEFAULT NULL,
`彎腰跪下或蹲下` varchar(25) DEFAULT NULL,
`走路超過1公里` varchar(25) DEFAULT NULL,
`走過數個街口` varchar(25) DEFAULT NULL,
`走過一個街口` varchar(25) DEFAULT NULL,
`自己洗澡或穿衣` varchar(25) DEFAULT NULL,
`做工作或其他活動的時間減少1` varchar(25) DEFAULT NULL,
`完成的工作量比您想要完成的少1` varchar(25) DEFAULT NULL,
`可以做的工作或其他活動的種類受到限制` varchar(25) DEFAULT NULL,
`做工作或其他活動有困難例如需更吃力` varchar(25) DEFAULT NULL,
`做工作或其他活動的時間減少2` varchar(25) DEFAULT NULL,
`完成的工作量比您想要完成的少2` varchar(25) DEFAULT NULL,
`做工作或其他活動時不如以往小心` varchar(25) DEFAULT NULL,
`Page10` varchar(25) DEFAULT NULL,
`在過去一個月內您的健康或情緒問題對您與家人或朋友鄰居社團間的平常活動的妨礙程度如何` varchar(25) DEFAULT NULL,
`在過去一個月內您的身體疼痛程度有多嚴重` varchar(25) DEFAULT NULL,
`在過去一個月內身體疼痛對您的日常工作包括上班及家務妨礙程度如何` varchar(25) DEFAULT NULL,
`您覺得充滿活力` varchar(25) DEFAULT NULL,
`您是一個非常緊張的人` varchar(25) DEFAULT NULL,
`您覺得非常沮喪沒有任何事情可以讓您高興起來` varchar(25) DEFAULT NULL,
`您覺得心情平靜` varchar(25) DEFAULT NULL,
`您精力充沛` varchar(25) DEFAULT NULL,
`您覺得悶悶不樂和憂鬱` varchar(25) DEFAULT NULL,
`您覺得筋疲力竭` varchar(25) DEFAULT NULL,
`您是一個快樂的人` varchar(25) DEFAULT NULL,
`您覺得累` varchar(25) DEFAULT NULL,
`在過去一個月內您的身體健康或情緒問題有多少時候會妨礙您的社交活動如拜訪親友等` varchar(25) DEFAULT NULL,
`我好像比別人較容易生病` varchar(25) DEFAULT NULL,
`和任何一個我認識的人來比我和他們一樣健康` varchar(25) DEFAULT NULL,
`我想我的健康會越來越壞` varchar(25) DEFAULT NULL,
`我的健康狀況好的很` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成1` varchar(25) DEFAULT NULL,
`Page11` varchar(25) DEFAULT NULL,
`過去一個月來您晚上通常幾點上床睡覺時24小時制` varchar(25) DEFAULT NULL,
`過去一個月來您晚上通常幾點上床睡覺分24小時制` varchar(25) DEFAULT NULL,
`過去一個月來您在上床後通常躺多久才能入睡幾分鐘` varchar(25) DEFAULT NULL,
`過去一個月來您早上通常幾點起床時24小時制` varchar(25) DEFAULT NULL,
`過去一個月來您早上通常幾點起床分24小時制` varchar(25) DEFAULT NULL,
`過去一個月來您每天晚上真正睡著的時間約多少這可能和您躺在床上所花時間不同時` varchar(25) DEFAULT NULL,
`過去一個月來您每天晚上真正睡著的時間約多少這可能和您躺在床上所花時間不同分` varchar(25) DEFAULT NULL,
`無法在30分鐘內入睡` varchar(25) DEFAULT NULL,
`半夜或凌晨便清醒` varchar(25) DEFAULT NULL,
`需要起床上廁所` varchar(25) DEFAULT NULL,
`呼吸不順暢` varchar(25) DEFAULT NULL,
`咳嗽或大聲打鼾` varchar(25) DEFAULT NULL,
`感覺很冷` varchar(25) DEFAULT NULL,
`感覺很熱` varchar(25) DEFAULT NULL,
`作惡夢` varchar(25) DEFAULT NULL,
`疼痛` varchar(25) DEFAULT NULL,
`其他情況請說明` varchar(25) DEFAULT NULL,
`其他說明` varchar(25) DEFAULT NULL,
`過去一個月來您有多少次需要藉助藥物醫師處方或成藥來幫助睡眠` varchar(25) DEFAULT NULL,
`過去一個月來當你在開車用餐從事日常社交活動時有多少次覺得難以保持清醒狀態` varchar(25) DEFAULT NULL,
`過去一個月來要打起精神來完成您應該做的事情對您有多少困擾` varchar(25) DEFAULT NULL,
`過去一個月來您對您自己的睡眠品質整體評價如何` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成2` varchar(25) DEFAULT NULL,
`Page12` varchar(25) DEFAULT NULL,
`我覺得緊張或神經緊繃` varchar(25) DEFAULT NULL,
`我依然享受我以前享受的事物` varchar(25) DEFAULT NULL,
`我有一種害怕的感覺好像有可怕的事即將發生` varchar(25) DEFAULT NULL,
`我能看到事情幽默的一面並且會心微笑` varchar(25) DEFAULT NULL,
`煩惱的念頭在我腦海中浮現` varchar(25) DEFAULT NULL,
`我覺得開心` varchar(25) DEFAULT NULL,
`我能輕鬆地坐著而且覺得放鬆` varchar(25) DEFAULT NULL,
`我覺得缺乏衝勁整個人都慢下來` varchar(25) DEFAULT NULL,
`我有一種忐忑不安的感覺七上八下的感覺` varchar(25) DEFAULT NULL,
`我對於自己的儀容失去興趣` varchar(25) DEFAULT NULL,
`我覺得焦躁不安想要不停的走動` varchar(25) DEFAULT NULL,
`我對未來的事抱有熱切期望` varchar(25) DEFAULT NULL,
`我突然感到恐慌` varchar(25) DEFAULT NULL,
`我能欣賞一本好書電台或電視節目` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成3` varchar(25) DEFAULT NULL,
`Page13` varchar(25) DEFAULT NULL,
`我缺乏友伴` varchar(25) DEFAULT NULL,
`我沒有可以依靠求助的對象` varchar(25) DEFAULT NULL,
`我是一個外向的人` varchar(25) DEFAULT NULL,
`我在人群中有被隔離孤立的感覺` varchar(25) DEFAULT NULL,
`當我需要幫助時我可以找到人幫我` varchar(25) DEFAULT NULL,
`我害羞退縮且不快樂` varchar(25) DEFAULT NULL,
`雖然我身邊有一些朋友但他們不是我的知己` varchar(25) DEFAULT NULL,
`我覺得自己不受他人重視` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成4` varchar(25) DEFAULT NULL,
`判斷力上的困難` varchar(25) DEFAULT NULL,
`對活動和嗜好的興趣降低` varchar(25) DEFAULT NULL,
`重複相同問題故事和陳述` varchar(25) DEFAULT NULL,
`在學習如何使用工具設備和小器具上有困難` varchar(25) DEFAULT NULL,
`忘記正確的月份和年份` varchar(25) DEFAULT NULL,
`處理複雜的財物上有困難` varchar(25) DEFAULT NULL,
`記住約會的時間有困難` varchar(25) DEFAULT NULL,
`有持續的思考和記憶方面的問題` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成5` varchar(25) DEFAULT NULL,
`Page14` varchar(25) DEFAULT NULL,
`您是否擔心您有記憶或其他思考問題` varchar(25) DEFAULT NULL,
`是這個狀況已經幾年` varchar(25) DEFAULT NULL,
`記得自己放東西的地方` varchar(25) DEFAULT NULL,
`記得現在的日期或星期幾` varchar(25) DEFAULT NULL,
`在與人對談中溝通想法` varchar(25) DEFAULT NULL,
`了解口頭指令或說明` varchar(25) DEFAULT NULL,
`當別人在駕車時幫忙看地圖並指路` varchar(25) DEFAULT NULL,
`在已經拜訪多次的房子裡認得路` varchar(25) DEFAULT NULL,
`預測天氣變化的能力和相應的計畫即帶外套或雨傘` varchar(25) DEFAULT NULL,
`預先想好事前規劃` varchar(25) DEFAULT NULL,
`保持生活與工作環境整齊` varchar(25) DEFAULT NULL,
`平衡收支帳簿沒有出錯` varchar(25) DEFAULT NULL,
`同時做兩件事的能力` varchar(25) DEFAULT NULL,
`在煮飯或工作時同時講話` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成6` varchar(25) DEFAULT NULL,
`Page15` varchar(25) DEFAULT NULL,
`過去三個月之中是否因食慾不佳消化問題咀嚼或吞嚥困難以致進食量越來越少` varchar(25) DEFAULT NULL,
`近三個月體重變化` varchar(25) DEFAULT NULL,
`行動力` varchar(25) DEFAULT NULL,
`過去三個月曾有精神性壓力或急性疾病發作` varchar(25) DEFAULT NULL,
`神經精神問題` varchar(25) DEFAULT NULL,
`可以獨立生活非住護理之家或醫院` varchar(25) DEFAULT NULL,
`每天需服用三種以上的處方藥物` varchar(25) DEFAULT NULL,
`褥瘡或皮膚潰瘍` varchar(25) DEFAULT NULL,
`一天中可以吃幾餐完整餐食` varchar(25) DEFAULT NULL,
`蛋白質攝取量` varchar(25) DEFAULT NULL,
`Page16` varchar(25) DEFAULT NULL,
`每天至少攝取二份或二份以上的蔬菜或水果` varchar(25) DEFAULT NULL,
`每天攝取多少液體包括開水果汁咖啡茶牛奶一杯240cc` varchar(25) DEFAULT NULL,
`進食的形式` varchar(25) DEFAULT NULL,
`自己覺得營養方面有沒有問題` varchar(25) DEFAULT NULL,
`與其他同年齡的人比較自己認為自己的健康狀況如何` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成7` varchar(25) DEFAULT NULL,
`走路穿越一個房間會困難嗎` varchar(25) DEFAULT NULL,
`您拿45公斤的物品是否感到困難` varchar(25) DEFAULT NULL,
`是否因為疾病或其他健康因素您從床上或椅子上站起來或坐下有困難` varchar(25) DEFAULT NULL,
`您能在沒有任何幫助的情況下獨立且不休息地連續爬10個台階嗎` varchar(25) DEFAULT NULL,
`過去一年中您跌倒過幾次` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成8` varchar(25) DEFAULT NULL,
`Page17` varchar(25) DEFAULT NULL,
`您曾經喝過酒包含藥酒補酒嗎` varchar(25) DEFAULT NULL,
`有幾歲開始喝酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒啤酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒中國酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒烈酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒水果酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒補藥酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒米酒` varchar(25) DEFAULT NULL,
`您常喝哪一種酒其他` varchar(25) DEFAULT NULL,
`其他酒` varchar(25) DEFAULT NULL,
`您喝酒喝幾年從第一次喝酒到最後一次喝酒` varchar(25) DEFAULT NULL,
`您是否曾戒過酒超過6個月未喝酒` varchar(25) DEFAULT NULL,
`已戒酒幾年未再喝` varchar(25) DEFAULT NULL,
`戒過幾年現在又喝` varchar(25) DEFAULT NULL,
`喝酒之後會不會臉紅` varchar(25) DEFAULT NULL,
`你多久喝一次酒` varchar(25) DEFAULT NULL,
`在一般喝酒的日子你一天可以喝多少酒精當量` varchar(25) DEFAULT NULL,
`多久會有一次喝超過六酒精當量的酒` varchar(25) DEFAULT NULL,
`過去一年中你發現一旦開始喝第一口酒後就會一直喝下去的情況有多常見` varchar(25) DEFAULT NULL,
`Page18` varchar(25) DEFAULT NULL,
`過去一年中因為喝酒而無法做你平常該做的事的情形有多常見` varchar(25) DEFAULT NULL,
`過去一年中經過一段時間的大量飲酒後早上需要喝一杯才會覺得舒服的情形有多常見` varchar(25) DEFAULT NULL,
`過去一年中在酒後覺得愧疚或自責的情形有多常見` varchar(25) DEFAULT NULL,
`過去一年中酒後忘記前一晚發生事情的情況有多常見` varchar(25) DEFAULT NULL,
`是否曾經有其他人或是你自己因為你的喝酒而受傷過` varchar(25) DEFAULT NULL,
`是否曾有親友醫生或其他醫事人員關心你喝酒的問題或是建議你少喝點` varchar(25) DEFAULT NULL,
`訪員確認上述量表是否完成9` varchar(25) DEFAULT NULL,
`面訪人員確認人員簽名` varchar(25) DEFAULT NULL,
`問卷收集情形` varchar(25) DEFAULT NULL,
`無法收集原因` varchar(25) DEFAULT NULL,
`資料收集情形` varchar(25) DEFAULT NULL,
`尚需補遺處理方式` varchar(25) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4
;

LOAD DATA LOCAL INFILE 
'D:/基隆長庚社區醫學科研究中心/CMRC社區資料庫/問卷匯入kaonthu/問卷_20211013_20211225/20211013_20211225.csv'
INTO TABLE kao_practice_6.CMRC_20211013_20211225_Q
CHARACTER SET utf8 FIELDS 
TERMINATED BY ','  
LINES TERMINATED BY '\n' 
IGNORE 1 LINES; 

UPDATE CMRC_DB_before.new_CMRC_db_20976_desc_20220127 as T1
INNER JOIN kao_practice_6.CMRC_20211013_20211225_Q as T2
ON T1.sid = T2.`流水號`
SET T1.`bloodtype`=T2.`血型ABO`,
T1.`bloodtype_rh`=T2.`血型Rh`,
T1.`diet`=T2.`飲食習慣`,
T1.`diet_1`=T2.`飲食習慣其他`,
T1.`education`=T2.`教育程度`,
T1.`job`=T2.`行業`,
T1.`job_1`=T2.`其他行業`,
T1.`job_t`=T2.`從事時間幾年`,
T1.`job_c`=T2.`工作類型`,
T1.`job_q`=T2.`仍在工作`,
T1.`job_qt`=T2.`已退休幾年`,
T1.`religion`=T2.`宗教信仰`,
T1.`religion_2`=T2.`其他宗教`,
T1.`f_clan`=T2.`親生父親氏族`,
T1.`f_land`=T2.`外省籍什麼省1`,
T1.`f_land1`=T2.`其他族1`,
T1.`m_clan`=T2.`親生母親氏族`,
T1.`m_land`=T2.`外省籍什麼省2`,
T1.`m_land1`=T2.`其他族2`,
T1.`mstatus`=T2.`婚姻狀況`,
T1.`marriyr`=T2.`結婚年數`,
T1.`children`=T2.`生育子女數`,
T1.`fam_self`=T2.`居住成員獨居`,
T1.`fam_p`=T2.`居住成員父母公婆`,
T1.`fam_sp`=T2.`居住成員配偶`,
T1.`fam_bs`=T2.`居住成員兄弟姊妹`,
T1.`fam_chi`=T2.`居住成員子女`,
T1.`child_num`=T2.`子女共幾人`,
T1.`fam_lawchi`=T2.`居住成員女婿媳婦`,
T1.`fam_grandchi`=T2.`居住成員孫子女`,
T1.`grandchild`=T2.`孫子共幾人`,
T1.`fam_o`=T2.`居住成員其他`,
T1.`others`=T2.`其他居住成員`,
T1.`live_place1`=T2.`從您出生到現在曾居住過最久的地方為什麼縣市`,
T1.`live_place2`=T2.`從您出生到現在曾居住過最久的地方為什麼區鄉鎮市`,
T1.`year1`=T2.`承上從民國幾年`,
T1.`year2`=T2.`至民國幾年`,
T1.`selfcare`=T2.`自我照護`,
T1.`care_self`=T2.`誰照顧你自理`,
T1.`care_p`=T2.`誰照顧你父母公婆`,
T1.`care_sp`=T2.`誰照顧你配偶`,
T1.`care_bs`=T2.`誰照顧你兄弟姊妹`,
T1.`care_chi`=T2.`誰照顧你子女`,
T1.`care_lawchi`=T2.`誰照顧你女婿媳婦`,
T1.`care_n`=T2.`誰照顧你看護`,
T1.`care_o`=T2.`誰照顧你其他`,
T1.`caregiver_1`=T2.`其他照顧你的人`,
T1.`eco_self`=T2.`經濟來源自己`,
T1.`eco_p`=T2.`經濟來源父母公婆`,
T1.`eco_sp`=T2.`經濟來源配偶`,
T1.`eco_bs`=T2.`經濟來源兄弟姊妹`,
T1.`eco_chi`=T2.`經濟來源子女`,
T1.`eco_lawchi`=T2.`經濟來源女婿媳婦`,
T1.`eco_gov`=T2.`經濟來源政府`,
T1.`eco_f`=T2.`經濟來源朋友`,
T1.`eco_o`=T2.`經濟來源其他`,
T1.`ecosource_1`=T2.`其他經濟來源`,
T1.`insurance`=T2.`保險狀況`,
T1.`insurance_1`=T2.`什麼保險`,
T1.`screening`=T2.`其他篩檢`,
T1.`screening_o`=T2.`參加其他篩檢名稱`,
T1.`together`=T2.`篩檢關聯性`,
T1.`together_1`=T2.`有親一同參加篩檢稱謂`,
T1.`together_2`=T2.`有親一同參加篩檢姓名`,
T1.`smoke`=T2.`您曾經抽過菸嗎`,
T1.`s_smoke`=T2.`幾歲開始抽菸`,
T1.`smoke_t`=T2.`您抽菸抽幾年`,
T1.`smoke_q`=T2.`您是否曾戒過菸`,
T1.`smoke_qt1`=T2.`已戒菸幾年未再抽`,
T1.`smoke_qt2`=T2.`戒過幾年現在又抽`,
T1.`smoke_f`=T2.`您抽菸的頻率`,
T1.`smoke_n`=T2.`您有抽菸的日子一天可以吸多少根菸`,
T1.`smoke_second`=T2.`您最近這一星期在家裡或工作地點有人抽煙或聞到菸味的頻率`,
T1.`tea`=T2.`您有喝茶的習慣嗎`,
T1.`tea_c`=T2.`您主要喝哪一種茶`,
T1.`tea_1`=T2.`混和以什麼茶為主`,
T1.`tea_t`=T2.`您喝茶喝幾年`,
T1.`tea_q`=T2.`您是否曾停止喝茶習慣超過6個月未喝`,
T1.`tea_f`=T2.`您喝茶的頻率`,
T1.`tea_v`=T2.`您有喝茶的日子一天可以喝多少CC的茶`,
T1.`coffee`=T2.`您有喝咖啡的習慣嗎`,
T1.`coffee_c`=T2.`您主要喝哪一種咖啡`,
T1.`coffee_t`=T2.`您喝咖啡喝幾年`,
T1.`coffee_q`=T2.`您是否曾停止喝咖啡習慣超過6個月未喝`,
T1.`coffee_f`=T2.`您喝咖啡的頻率`,
T1.`coffee_v`=T2.`您有喝咖啡的日子一天可以喝多少CC的咖啡`,
T1.`betel`=T2.`您曾經嚼過檳榔嗎`,
T1.`s_betel`=T2.`幾歲開始嚼檳榔`,
T1.`betel_clt1`=T2.`您主要嚼哪一類檳榔加荖藤`,
T1.`betel_clt2`=T2.`您主要嚼哪一類檳榔加荖葉`,
T1.`betel_clt3`=T2.`您主要嚼哪一類檳榔紅灰`,
T1.`betel_clt4`=T2.`您主要嚼哪一類檳榔白灰`,
T1.`betel_clt5`=T2.`您主要嚼哪一類檳榔菁仔`,
T1.`betel_clt6`=T2.`您主要嚼哪一類檳榔其他`,
T1.`betel_o`=T2.`其他種類檳榔`,
T1.`betel_t`=T2.`您嚼檳榔嚼幾年`,
T1.`betel_q`=T2.`您是否曾停止嚼檳榔習慣超過6個月未嚼`,
T1.`betel_f`=T2.`您嚼檳榔的平均頻率`,
T1.`betel_n`=T2.`您有嚼檳榔的日子一天可以嚼幾顆檳榔`,
T1.`hypertension`=T2.`自己有無高血壓`,
T1.`Dysrhythmia`=T2.`自己有無心律不整`,
T1.`ap`=T2.`自己有無心絞痛`,
T1.`ami`=T2.`自己有無心肌梗塞`,
T1.`Hyperlipidemia`=T2.`自己有無高血脂`,
T1.`HF`=T2.`自己有無心臟衰竭`,
T1.`diabetes`=T2.`自己有無糖尿病`,
T1.`Thyroid`=T2.`自己有無甲狀腺疾病`,
T1.`pepticulcer`=T2.`自己有無胃或十二指腸潰瘍`,
T1.`hbv`=T2.`自己有無B肝`,
T1.`hcv`=T2.`自己有無C肝`,
T1.`FLD`=T2.`自己有無脂肪肝`,
T1.`fibrosis`=T2.`自己有無肝纖維化`,
T1.`Cirrhosis`=T2.`自己有無肝硬化`,
T1.`Polyposis`=T2.`自己有無大腸瘜肉`,
T1.`ibs`=T2.`自己有無腸躁症`,
T1.`Asthma`=T2.`自己有無氣喘`,
T1.`apnea`=T2.`自己有無呼吸中止`,
T1.`copd`=T2.`自己有無慢性阻塞性肺病`,
T1.`anemia`=T2.`自己有無貧血`,
T1.`Hemophilia`=T2.`自己有無血友病`,
T1.`f_hyper`=T2.`親生父親有無高血壓`,
T1.`f_dys`=T2.`親生父親有無心律不整`,
T1.`f_ap`=T2.`親生父親有無心絞痛`,
T1.`f_ami`=T2.`親生父親有無心肌梗塞`,
T1.`f_lipid`=T2.`親生父親有無高血脂`,
T1.`f_hf`=T2.`親生父親有無心臟衰竭`,
T1.`f_dm`=T2.`親生父親有無糖尿病`,
T1.`f_Thyroid`=T2.`親生父親有無甲狀腺疾病`,
T1.`f_pud`=T2.`親生父親有無胃或十二指腸潰瘍`,
T1.`f_hbv`=T2.`親生父親有無B肝`,
T1.`f_hcv`=T2.`親生父親有無C肝`,
T1.`f_fld`=T2.`親生父親有無脂肪肝`,
T1.`f_f`=T2.`親生父親有無肝纖維化`,
T1.`f_lc`=T2.`親生父親有無肝硬化`,
T1.`f_polyp`=T2.`親生父親有無大腸瘜肉`,
T1.`f_ibs`=T2.`親生父親有無腸躁症`,
T1.`f_Asthma`=T2.`親生父親有無氣喘`,
T1.`f_apnea`=T2.`親生父親有無呼吸中止`,
T1.`f_copd`=T2.`親生父親有無慢性阻塞性肺病`,
T1.`f_anemia`=T2.`親生父親有無貧血`,
T1.`f_h`=T2.`親生父親有無血友病`,
T1.`m_hyper`=T2.`親生母親有無高血壓`,
T1.`m_dys`=T2.`親生母親有無心律不整`,
T1.`m_ap`=T2.`親生母親有無心絞痛`,
T1.`m_ami`=T2.`親生母親有無心肌梗塞`,
T1.`m_lipid`=T2.`親生母親有無高血脂`,
T1.`m_hf`=T2.`親生母親有無心臟衰竭`,
T1.`m_dm`=T2.`親生母親有無糖尿病`,
T1.`m_Thyroid`=T2.`親生母親有無甲狀腺疾病`,
T1.`m_pud`=T2.`親生母親有無胃或十二指腸潰瘍`,
T1.`m_hbv`=T2.`親生母親有無B肝`,
T1.`m_hcv`=T2.`親生母親有無C肝`,
T1.`m_fld`=T2.`親生母親有無脂肪肝`,
T1.`m_f`=T2.`親生母親有無肝纖維化`,
T1.`m_lc`=T2.`親生母親有無肝硬化`,
T1.`m_polyp`=T2.`親生母親有無大腸瘜肉`,
T1.`m_ibs`=T2.`親生母親有無腸躁症`,
T1.`m_Asthma`=T2.`親生母親有無氣喘`,
T1.`m_apnea`=T2.`親生母親有無呼吸中止`,
T1.`m_copd`=T2.`親生母親有無慢性阻塞性肺病`,
T1.`m_anemia`=T2.`親生母親有無貧血`,
T1.`m_h`=T2.`親生母親有無血友病`,
T1.`bs_hyper`=T2.`兄弟姊妹有無高血壓`,
T1.`bs_hyper_1`=T2.`兄弟姊妹誰患高血壓`,
T1.`bs_dys`=T2.`兄弟姊妹有無心律不整`,
T1.`bs_dys_1`=T2.`兄弟姊妹誰患心律不整`,
T1.`bs_ap`=T2.`兄弟姊妹有無心絞痛`,
T1.`bs_ap1`=T2.`兄弟姊妹誰患心絞痛`,
T1.`bs_ami`=T2.`兄弟姊妹有無心肌梗塞`,
T1.`bs_ami_1`=T2.`兄弟姊妹誰患心肌梗塞`,
T1.`bs_lipid`=T2.`兄弟姊妹有無高血脂`,
T1.`bs_lipid_1`=T2.`兄弟姊妹誰患高血脂`,
T1.`bs_hf`=T2.`兄弟姊妹有無心臟衰竭`,
T1.`bs_hf_1`=T2.`兄弟姊妹誰患心臟衰竭`,
T1.`bs_dm`=T2.`兄弟姊妹有無糖尿病`,
T1.`bs_dm_1`=T2.`兄弟姊妹誰患糖尿病`,
T1.`bs_Thyroid`=T2.`兄弟姊妹有無甲狀腺疾病`,
T1.`bs_Thyroid_1`=T2.`兄弟姊妹誰患甲狀腺疾病`,
T1.`bs_pud`=T2.`兄弟姊妹有無胃或十二指腸潰瘍`,
T1.`bs_pud_1`=T2.`兄弟姊妹誰患胃或十二指腸潰瘍`,
T1.`bs_hbv`=T2.`兄弟姊妹有無B肝`,
T1.`bs_hbv_1`=T2.`兄弟姊妹誰患B肝`,
T1.`bs_hcv`=T2.`兄弟姊妹有無C肝`,
T1.`bs_hcv_1`=T2.`兄弟姊妹誰患C肝`,
T1.`bs_fld`=T2.`兄弟姊妹有無脂肪肝`,
T1.`bs_fld_1`=T2.`兄弟姊妹誰患脂肪肝`,
T1.`bs_f`=T2.`兄弟姊妹有無肝纖維化`,
T1.`bs_f_1`=T2.`兄弟姊妹誰患肝纖維化`,
T1.`bs_lc`=T2.`兄弟姊妹有無肝硬化`,
T1.`bs_lc_1`=T2.`兄弟姊妹誰患肝硬化`,
T1.`bs_polyp`=T2.`兄弟姊妹有無大腸瘜肉`,
T1.`bs_polyp_1`=T2.`兄弟姊妹誰患大腸瘜肉`,
T1.`bs_ibs`=T2.`兄弟姊妹有無腸躁症`,
T1.`bs_ibs_1`=T2.`兄弟姊妹誰患腸躁症`,
T1.`bs_Asthma`=T2.`兄弟姊妹有無氣喘`,
T1.`bs_Asthma_1`=T2.`兄弟姊妹誰患氣喘`,
T1.`bs_apnea`=T2.`兄弟姊妹有無呼吸中止`,
T1.`bs_apnea_1`=T2.`兄弟姊妹誰患呼吸中止`,
T1.`bs_copd`=T2.`兄弟姊妹有無慢性阻塞性肺病`,
T1.`bs_copd_1`=T2.`兄弟姊妹誰患慢性阻塞性肺病`,
T1.`bs_anemia`=T2.`兄弟姊妹有無貧血`,
T1.`bs_anemia_1`=T2.`兄弟姊妹誰患貧血`,
T1.`bs_h`=T2.`兄弟姊妹有無血友病`,
T1.`bs_h_1`=T2.`兄弟姊妹誰患血友病`,
T1.`chi_hyper`=T2.`子女有無高血壓`,
T1.`chi_dys`=T2.`子女有無心律不整`,
T1.`chi_ap`=T2.`子女有無心絞痛`,
T1.`chi_ami`=T2.`子女有無心肌梗塞`,
T1.`chi_lipid`=T2.`子女有無高血脂`,
T1.`chi_hf`=T2.`子女有無心臟衰竭`,
T1.`chi_dm`=T2.`子女有無糖尿病`,
T1.`chi_Thyroid`=T2.`子女有無甲狀腺疾病`,
T1.`chi_pud`=T2.`子女有無胃或十二指腸潰瘍`,
T1.`chi_hbv`=T2.`子女有無B肝`,
T1.`chi_hcv`=T2.`子女有無C肝`,
T1.`chi_fld`=T2.`子女有無脂肪肝`,
T1.`chi_f`=T2.`子女有無肝纖維化`,
T1.`chi_lc`=T2.`子女有無肝硬化`,
T1.`chi_polyp`=T2.`子女有無大腸瘜肉`,
T1.`chi_ibs`=T2.`子女有無腸躁症`,
T1.`chi_Asthma`=T2.`子女有無氣喘`,
T1.`chi_apnea`=T2.`子女有無呼吸中止`,
T1.`chi_copd`=T2.`子女有無慢性阻塞性肺病`,
T1.`chi_anemia`=T2.`子女有無貧血`,
T1.`chi_h`=T2.`子女有無血友病`,
T1.`stroke`=T2.`自己有無腦中風`,
T1.`brainbleed`=T2.`自己有無腦出血`,
T1.`head_injury`=T2.`自己有無腦外傷開刀`,
T1.`epilepsy`=T2.`自己有無癲癇`,
T1.`Parkinsons`=T2.`自己有無巴金森氏症`,
T1.`dementia`=T2.`自己有無失智`,
T1.`Huntingtons`=T2.`自己有無舞蹈症`,
T1.`Depression`=T2.`自己有無憂鬱症`,
T1.`mdd_dx`=T2.`自己憂鬱症有過醫師診斷`,
T1.`mental`=T2.`自己有無其他精神科疾病`,
T1.`ckd`=T2.`自己有無慢性腎病`,
T1.`dialysis`=T2.`自己有無洗腎`,
T1.`stone`=T2.`自己有無結石`,
T1.`bpn`=T2.`自己有無攝護腺肥大`,
T1.`cataract`=T2.`自己有無白內障`,
T1.`glau`=T2.`自己有無青光眼`,
T1.`retina`=T2.`自己有無視網膜病變`,
T1.`sicca`=T2.`自己有無乾眼症`,
T1.`lungcan`=T2.`自己有無肺癌`,
T1.`breastcna`=T2.`自己有無乳癌`,
T1.`colican`=T2.`自己有無大腸癌`,
T1.`gastrican`=T2.`自己有無胃癌`,
T1.`livercan`=T2.`自己有無肝癌`,
T1.`cancer_o`=T2.`自己有無其他癌症`,
T1.`f_stroke`=T2.`親生父親有無腦中風`,
T1.`f_brainbleed`=T2.`親生父親有無腦出血`,
T1.`f_hi`=T2.`親生父親有無腦外傷開刀`,
T1.`f_epilep`=T2.`親生父親有無癲癇`,
T1.`f_pd`=T2.`親生父親有無巴金森氏症`,
T1.`f_demen`=T2.`親生父親有無失智`,
T1.`f_hd`=T2.`親生父親有無舞蹈症`,
T1.`f_mdd`=T2.`親生父親有無憂鬱症`,
T1.`f_mdd_dx`=T2.`親生父親憂鬱症有過醫師診斷`,
T1.`f_mental`=T2.`親生父親有無其他精神科疾病`,
T1.`f_ckd`=T2.`親生父親有無慢性腎病`,
T1.`f_dialysis`=T2.`親生父親有無洗腎`,
T1.`f_stone`=T2.`親生父親有無結石`,
T1.`f_bpn`=T2.`親生父親有無攝護腺肥大`,
T1.`f_cata`=T2.`親生父親有無白內障`,
T1.`f_glau`=T2.`親生父親有無青光眼`,
T1.`f_retina`=T2.`親生父親有無視網膜病變`,
T1.`f_sicca`=T2.`親生父親有無乾眼症`,
T1.`f_lung`=T2.`親生父親有無肺癌`,
T1.`f_breast`=T2.`親生父親有無乳癌`,
T1.`f_coli`=T2.`親生父親有無大腸癌`,
T1.`f_gastric`=T2.`親生父親有無胃癌`,
T1.`f_liver_c`=T2.`親生父親有無肝癌`,
T1.`f_can_o`=T2.`親生父親有無其他癌症`,
T1.`m_stroke`=T2.`親生母親有無腦中風`,
T1.`m_brainbleed`=T2.`親生母親有無腦出血`,
T1.`m_hi`=T2.`親生母親有無腦外傷開刀`,
T1.`m_epilep`=T2.`親生母親有無癲癇`,
T1.`m_pd`=T2.`親生母親有無巴金森氏症`,
T1.`m_demen`=T2.`親生母親有無失智`,
T1.`m_hd`=T2.`親生母親有無舞蹈症`,
T1.`m_mdd`=T2.`親生母親有無憂鬱症`,
T1.`m_mdd_dx`=T2.`親生母親憂鬱症有過醫師診斷`,
T1.`m_mental`=T2.`親生母親有無其他精神科疾病`,
T1.`m_ckd`=T2.`親生母親有無慢性腎病`,
T1.`m_dialysis`=T2.`親生母親有無洗腎`,
T1.`m_stone`=T2.`親生母親有無結石`,
T1.`m_bpn`=T2.`親生母親有無攝護腺肥大`,
T1.`m_cata`=T2.`親生母親有無白內障`,
T1.`m_glau`=T2.`親生母親有無青光眼`,
T1.`m_retina`=T2.`親生母親有無視網膜病變`,
T1.`m_sicca`=T2.`親生母親有無乾眼症`,
T1.`m_lung`=T2.`親生母親有無肺癌`,
T1.`m_breast`=T2.`親生母親有無乳癌`,
T1.`m_coli`=T2.`親生母親有無大腸癌`,
T1.`m_gastric`=T2.`親生母親有無胃癌`,
T1.`m_liver_c`=T2.`親生母親有無肝癌`,
T1.`m_can_o`=T2.`親生母親有無其他癌症`,
T1.`bs_stroke`=T2.`兄弟姊妹有無腦中風`,
T1.`bs_stroke_1`=T2.`兄弟姊妹誰患腦中風`,
T1.`bs_brainbleed`=T2.`兄弟姊妹有無腦出血`,
T1.`bs_brainbleed_1`=T2.`兄弟姊妹誰患腦出血`,
T1.`bs_hi`=T2.`兄弟姊妹有無腦外傷開刀`,
T1.`bs_hi_1`=T2.`兄弟姊妹誰患腦外傷開刀`,
T1.`bs_epilep`=T2.`兄弟姊妹有無癲癇`,
T1.`bs_epilep_1`=T2.`兄弟姊妹誰患癲癇`,
T1.`bs_pd`=T2.`兄弟姊妹有無巴金森氏症`,
T1.`bs_pd_1`=T2.`兄弟姊妹誰患巴金森氏症`,
T1.`bs_demen`=T2.`兄弟姊妹有無失智`,
T1.`bs_demen_1`=T2.`兄弟姊妹誰患失智`,
T1.`bs_hd`=T2.`兄弟姊妹有無舞蹈症`,
T1.`bs_hd_1`=T2.`兄弟姊妹誰患舞蹈症`,
T1.`bs_mdd`=T2.`兄弟姊妹有無憂鬱症`,
T1.`bs_mdd_1`=T2.`兄弟姊妹誰患憂鬱症`,
T1.`bs_mdd_dx`=T2.`兄弟妹憂鬱症有過醫師診斷`,
T1.`bs_mental`=T2.`兄弟姊妹有無其他精神科疾病`,
T1.`bs_ckd`=T2.`兄弟姊妹有無慢性腎病`,
T1.`bs_ckd_1`=T2.`兄弟姊妹誰患慢性腎病`,
T1.`bs_dialysis`=T2.`兄弟姊妹有無洗腎`,
T1.`bs_dialysis_1`=T2.`兄弟姊妹誰患洗腎`,
T1.`bs_stone`=T2.`兄弟姊妹有無結石`,
T1.`bs_stone_1`=T2.`兄弟姊妹誰患結石`,
T1.`bs_bpn`=T2.`兄弟姊妹有無攝護腺肥大`,
T1.`bs_bpn_1`=T2.`兄弟姊妹誰患攝護腺肥大`,
T1.`bs_cata`=T2.`兄弟姊妹有無白內障`,
T1.`bs_cata_1`=T2.`兄弟姊妹誰患白內障`,
T1.`bs_glau`=T2.`兄弟姊妹有無青光眼`,
T1.`bs_glau_1`=T2.`兄弟姊妹誰患青光眼`,
T1.`bs_retina`=T2.`兄弟姊妹有無視網膜病變`,
T1.`bs_retina_1`=T2.`兄弟姊妹誰患視網膜病變`,
T1.`bs_sicca`=T2.`兄弟姊妹有無乾眼症`,
T1.`bs_sicca_1`=T2.`兄弟姊妹誰患乾眼症`,
T1.`bs_lung`=T2.`兄弟姊妹有無肺癌`,
T1.`bs_lung_1`=T2.`兄弟姊妹誰患肺癌`,
T1.`bs_breast`=T2.`兄弟姊妹有無乳癌`,
T1.`bs_breast_1`=T2.`兄弟姊妹誰患乳癌`,
T1.`bs_coli`=T2.`兄弟姊妹有無大腸癌`,
T1.`bs_coli_1`=T2.`兄弟姊妹誰患大腸癌`,
T1.`bs_gastric`=T2.`兄弟姊妹有無胃癌`,
T1.`bs_gastric_1`=T2.`兄弟姊妹誰患胃癌`,
T1.`bs_liver_c`=T2.`兄弟姊妹有無肝癌`,
T1.`bs_liver_c_1`=T2.`兄弟姊妹誰患肝癌`,
T1.`bs_can_o`=T2.`兄弟姊妹有無其他癌症`,
T1.`chi_stroke`=T2.`子女有無腦中風`,
T1.`chi_brainbleed`=T2.`子女有無腦出血`,
T1.`chi_hi`=T2.`子女有無腦外傷開刀`,
T1.`chi_epilep`=T2.`子女有無癲癇`,
T1.`chi_pd`=T2.`子女有無巴金森氏症`,
T1.`chi_demen`=T2.`子女有無失智`,
T1.`chi_hd`=T2.`子女有無舞蹈症`,
T1.`chi_mdd`=T2.`子女有無憂鬱症`,
T1.`chi_mdd_dx`=T2.`子女憂鬱症有過醫師診斷`,
T1.`chi_mental`=T2.`子女有無其他精神科疾病`,
T1.`chi_ckd`=T2.`子女有無慢性腎病`,
T1.`chi_dialysis`=T2.`子女有無洗腎`,
T1.`chi_stone`=T2.`子女有無結石`,
T1.`chi_bpn`=T2.`子女有無攝護腺肥大`,
T1.`chi_cata`=T2.`子女有無白內障`,
T1.`chi_glau`=T2.`子女有無青光眼`,
T1.`chi_retina`=T2.`子女有無視網膜病變`,
T1.`chi_sicca`=T2.`子女有無乾眼症`,
T1.`chi_lung`=T2.`子女有無肺癌`,
T1.`chi_breast`=T2.`子女有無乳癌`,
T1.`chi_coli`=T2.`子女有無大腸癌`,
T1.`chi_gastric`=T2.`子女有無胃癌`,
T1.`chi_liver_c`=T2.`子女有無肝癌`,
T1.`chi_can_o`=T2.`子女有無其他癌症`,
T1.`ndisease`=T2.`自己無以上病史`,
T1.`UNKNOWN`=T2.`自己不知道`,
T1.`dis_o`=T2.`自己其他未列出疾病`,
T1.`fn`=T2.`親生父親無以上病史`,
T1.`funknown`=T2.`親生父親不知道`,
T1.`f_dis_o`=T2.`親生父親其他未列出疾病`,
T1.`mn`=T2.`親生母親無以上病史`,
T1.`munknown`=T2.`親生母親不知道`,
T1.`m_dis_o`=T2.`親生母親其他未列出疾病`,
T1.`bsn`=T2.`兄弟姊妹無以上病史`,
T1.`bsunknown`=T2.`兄弟姊妹不知道`,
T1.`bs_dis_o`=T2.`兄弟姊妹其他未列出疾病`,
T1.`chin`=T2.`子女無以上病史`,
T1.`chiunknown`=T2.`子女不知道`,
T1.`chi_dis_o`=T2.`子女其他未列出疾病`,
T1.`Syr_drug`=T2.`您是否常服用咳嗽糖漿`,
T1.`Hypnotic`=T2.`您是否常服用安眠藥`,
T1.`drug`=T2.`您是否常服用止痛抗發炎類藥物包括針劑`,
T1.`hyper_drug`=T2.`您是否正在服用高血壓藥物包括針劑`,
T1.`dm_drug`=T2.`您是否正在服用糖尿病藥物包括針劑`,
T1.`hor_drug`=T2.`您是否正在服用賀爾蒙藥物包括針劑`,
T1.`lipiddrug`=T2.`您是否正在服用降血脂藥物包括針劑`,
T1.`gasdrug`=T2.`請問您最近兩星期是否有吃胃藥`,
T1.`cmed`=T2.`您是否有吃中草藥的習慣非藥酒`,
T1.`hf_none`=T2.`請問您是否有吃下列食品的習慣否`,
T1.`hf_vit`=T2.`請問您是否有吃下列食品的習慣維他命`,
T1.`hf_wgl`=T2.`請問您是否有吃下列食品的習慣維骨力或葡萄糖胺`,
T1.`hf_foil`=T2.`請問您是否有吃下列食品的習慣魚肝油`,
T1.`hf_ca`=T2.`請問您是否有吃下列食品的習慣鈣片`,
T1.`hf_p1`=T2.`請問您是否有吃下列食品的習慣人蔘`,
T1.`hf_p2`=T2.`請問您是否有吃下列食品的習慣靈芝`,
T1.`hf_chic`=T2.`請問您是否有吃下列食品的習慣雞精`,
T1.`hf_clam`=T2.`請問您是否有吃下列食品的習慣蜆精`,
T1.`hf_e`=T2.`請問您是否有吃下列食品的習慣提神飲料`,
T1.`hf_lutein`=T2.`請問您是否有吃下列食品的習慣葉黃素`,
T1.`hf_collagen`=T2.`請問您是否有吃下列食品的習慣膠原蛋白`,
T1.`hf_other`=T2.`請問您是否有吃下列食品的習慣其他`,
T1.`hf_1`=T2.`其他食品`,
T1.`plastic_1`=T2.`您常使用塑膠袋盛裝熱食`,
T1.`plastic_2`=T2.`您常使用塑膠餐具`,
T1.`plastic_3`=T2.`您常吃有包裝的加工食品`,
T1.`plastic_4`=T2.`您家中常使用保鮮膜進行微波蒸煮或包裝油性食物嗎`,
T1.`plastic_5`=T2.`您常喝市售的塑膠杯裝的飲料`,
T1.`plastic_6`=T2.`您常使用有香氣的衛浴用品嗎`,
T1.`plastic_7`=T2.`您家中使用塑膠地墊嗎`,
T1.`BI_1`=T2.`請問您是否曾經中風`,
T1.`BI_2`=T2.`請問您是否曾因跌倒車禍或外力傷害撞擊到頭部`,
T1.`BI_3`=T2.`若曾經有過上述1或2的情形請問您當時是否意識清醒`,
T1.`SF36_1`=T2.`一般來說您認為您目前的健康狀況是`,
T1.`SF36_2`=T2.`和一年前比較您認為您目前的健康狀況是`,
T1.`sf36_3_a`=T2.`費力活動跑步提重物參與劇烈運動`,
T1.`sf36_3_b`=T2.`中等程度活動搬桌子拖地或打太極拳`,
T1.`sf36_3_c`=T2.`提起或攜帶食品雜貨`,
T1.`sf36_3_d`=T2.`爬數層樓樓梯`,
T1.`sf36_3_e`=T2.`爬一層樓樓梯`,
T1.`sf36_3_f`=T2.`彎腰跪下或蹲下`,
T1.`sf36_3_g`=T2.`走路超過1公里`,
T1.`sf36_3_h`=T2.`走過數個街口`,
T1.`sf36_3_i`=T2.`走過一個街口`,
T1.`sf36_3_j`=T2.`自己洗澡或穿衣`,
T1.`sf36_4_a`=T2.`做工作或其他活動的時間減少1`,
T1.`sf36_4_b`=T2.`完成的工作量比您想要完成的少1`,
T1.`sf36_4_c`=T2.`可以做的工作或其他活動的種類受到限制`,
T1.`sf36_4_d`=T2.`做工作或其他活動有困難例如需更吃力`,
T1.`sf36_5_a`=T2.`做工作或其他活動的時間減少2`,
T1.`sf36_5_b`=T2.`完成的工作量比您想要完成的少2`,
T1.`sf36_5_c`=T2.`做工作或其他活動時不如以往小心`,
T1.`sf36_6`=T2.`在過去一個月內您的健康或情緒問題對您與家人或朋友鄰居社團間的平常活動的妨礙程度如何`,
T1.`sf36_7`=T2.`在過去一個月內您的身體疼痛程度有多嚴重`,
T1.`sf36_8`=T2.`在過去一個月內身體疼痛對您的日常工作包括上班及家務妨礙程度如何`,
T1.`sf36_9_a`=T2.`您覺得充滿活力`,
T1.`sf36_9_b`=T2.`您是一個非常緊張的人`,
T1.`sf36_9_c`=T2.`您覺得非常沮喪沒有任何事情可以讓您高興起來`,
T1.`sf36_9_d`=T2.`您覺得心情平靜`,
T1.`sf36_9_e`=T2.`您精力充沛`,
T1.`sf36_9_f`=T2.`您覺得悶悶不樂和憂鬱`,
T1.`sf36_9_g`=T2.`您覺得筋疲力竭`,
T1.`sf36_9_h`=T2.`您是一個快樂的人`,
T1.`sf36_9_i`=T2.`您覺得累`,
T1.`sf36_10`=T2.`在過去一個月內您的身體健康或情緒問題有多少時候會妨礙您的社交活動如拜訪親友等`,
T1.`sf36_11_a`=T2.`我好像比別人較容易生病`,
T1.`sf36_11_b`=T2.`和任何一個我認識的人來比我和他們一樣健康`,
T1.`sf36_11_c`=T2.`我想我的健康會越來越壞`,
T1.`sf36_11_d`=T2.`我的健康狀況好的很`,
T1.`check5`=T2.`訪員確認上述量表是否完成1`,
T1.`beda`=T2.`過去一個月來您晚上通常幾點上床睡覺時24小時制`,
T1.`bedb`=T2.`過去一個月來您晚上通常幾點上床睡覺分24小時制`,
T1.`bedt`=T2.`過去一個月來您在上床後通常躺多久才能入睡幾分鐘`,
T1.`waketa`=T2.`過去一個月來您早上通常幾點起床時24小時制`,
T1.`waketb`=T2.`過去一個月來您早上通常幾點起床分24小時制`,
T1.`sleepta`=T2.`過去一個月來您每天晚上真正睡著的時間約多少這可能和您躺在床上所花時間不同時`,
T1.`sleeptb`=T2.`過去一個月來您每天晚上真正睡著的時間約多少這可能和您躺在床上所花時間不同分`,
T1.`sleep1`=T2.`無法在30分鐘內入睡`,
T1.`sleep2`=T2.`半夜或凌晨便清醒`,
T1.`sleep3`=T2.`需要起床上廁所`,
T1.`sleep4`=T2.`呼吸不順暢`,
T1.`sleep5`=T2.`咳嗽或大聲打鼾`,
T1.`sleep6`=T2.`感覺很冷`,
T1.`sleep7`=T2.`感覺很熱`,
T1.`sleep8`=T2.`作惡夢`,
T1.`sleep9`=T2.`疼痛`,
T1.`sleep10`=T2.`其他情況請說明`,
T1.`sleep10a`=T2.`其他說明`,
T1.`sleep12`=T2.`過去一個月來您有多少次需要藉助藥物醫師處方或成藥來幫助睡眠`,
T1.`sleep13`=T2.`過去一個月來當你在開車用餐從事日常社交活動時有多少次覺得難以保持清醒狀態`,
T1.`sleep14`=T2.`過去一個月來要打起精神來完成您應該做的事情對您有多少困擾`,
T1.`sleep11`=T2.`過去一個月來您對您自己的睡眠品質整體評價如何`,
T1.`check6`=T2.`訪員確認上述量表是否完成2`,
T1.`hads_1`=T2.`我覺得緊張或神經緊繃`,
T1.`hads_2`=T2.`我依然享受我以前享受的事物`,
T1.`hads_3`=T2.`我有一種害怕的感覺好像有可怕的事即將發生`,
T1.`hads_4`=T2.`我能看到事情幽默的一面並且會心微笑`,
T1.`hads_5`=T2.`煩惱的念頭在我腦海中浮現`,
T1.`hads_6`=T2.`我覺得開心`,
T1.`hads_7`=T2.`我能輕鬆地坐著而且覺得放鬆`,
T1.`hads_8`=T2.`我覺得缺乏衝勁整個人都慢下來`,
T1.`hads_9`=T2.`我有一種忐忑不安的感覺七上八下的感覺`,
T1.`hads_10`=T2.`我對於自己的儀容失去興趣`,
T1.`hads_11`=T2.`我覺得焦躁不安想要不停的走動`,
T1.`hads_12`=T2.`我對未來的事抱有熱切期望`,
T1.`hads_13`=T2.`我突然感到恐慌`,
T1.`hads_14`=T2.`我能欣賞一本好書電台或電視節目`,
T1.`check7`=T2.`訪員確認上述量表是否完成3`,
T1.`uls8_1`=T2.`我缺乏友伴`,
T1.`uls8_2`=T2.`我沒有可以依靠求助的對象`,
T1.`uls8_3`=T2.`我是一個外向的人`,
T1.`uls8_4`=T2.`我在人群中有被隔離孤立的感覺`,
T1.`uls8_5`=T2.`當我需要幫助時我可以找到人幫我`,
T1.`uls8_6`=T2.`我害羞退縮且不快樂`,
T1.`uls8_7`=T2.`雖然我身邊有一些朋友但他們不是我的知己`,
T1.`uls8_8`=T2.`我覺得自己不受他人重視`,
T1.`check8`=T2.`訪員確認上述量表是否完成4`,
T1.`ad8_1`=T2.`判斷力上的困難`,
T1.`ad8_2`=T2.`對活動和嗜好的興趣降低`,
T1.`ad8_3`=T2.`重複相同問題故事和陳述`,
T1.`ad8_4`=T2.`在學習如何使用工具設備和小器具上有困難`,
T1.`ad8_5`=T2.`忘記正確的月份和年份`,
T1.`ad8_6`=T2.`處理複雜的財物上有困難`,
T1.`ad8_7`=T2.`記住約會的時間有困難`,
T1.`ad8_8`=T2.`有持續的思考和記憶方面的問題`,
T1.`check9`=T2.`訪員確認上述量表是否完成5`,
T1.`ecog12a`=T2.`您是否擔心您有記憶或其他思考問題`,
T1.`ecog12a1`=T2.`是這個狀況已經幾年`,
T1.`ecog12b1`=T2.`記得自己放東西的地方`,
T1.`ecog12b2`=T2.`記得現在的日期或星期幾`,
T1.`ecog12b3`=T2.`在與人對談中溝通想法`,
T1.`ecog12b4`=T2.`了解口頭指令或說明`,
T1.`ecog12b5`=T2.`當別人在駕車時幫忙看地圖並指路`,
T1.`ecog12b6`=T2.`在已經拜訪多次的房子裡認得路`,
T1.`ecog12b7`=T2.`預測天氣變化的能力和相應的計畫即帶外套或雨傘`,
T1.`ecog12b8`=T2.`預先想好事前規劃`,
T1.`ecog12b9`=T2.`保持生活與工作環境整齊`,
T1.`ecog12b10`=T2.`平衡收支帳簿沒有出錯`,
T1.`ecog12b11`=T2.`同時做兩件事的能力`,
T1.`ecog12b12`=T2.`在煮飯或工作時同時講話`,
T1.`check10`=T2.`訪員確認上述量表是否完成6`,
T1.`mna_1`=T2.`過去三個月之中是否因食慾不佳消化問題咀嚼或吞嚥困難以致進食量越來越少`,
T1.`mna_2`=T2.`近三個月體重變化`,
T1.`mna_3`=T2.`行動力`,
T1.`mna_4`=T2.`過去三個月曾有精神性壓力或急性疾病發作`,
T1.`mna_5`=T2.`神經精神問題`,
T1.`mna_6`=T2.`可以獨立生活非住護理之家或醫院`,
T1.`mna_7`=T2.`每天需服用三種以上的處方藥物`,
T1.`mna_8`=T2.`褥瘡或皮膚潰瘍`,
T1.`mna_9`=T2.`一天中可以吃幾餐完整餐食`,
T1.`mna_10`=T2.`蛋白質攝取量`,
T1.`mna_11`=T2.`每天至少攝取二份或二份以上的蔬菜或水果`,
T1.`mna_12`=T2.`每天攝取多少液體包括開水果汁咖啡茶牛奶一杯240cc`,
T1.`mna_13`=T2.`進食的形式`,
T1.`mna_14`=T2.`自己覺得營養方面有沒有問題`,
T1.`mna_15`=T2.`與其他同年齡的人比較自己認為自己的健康狀況如何`,
T1.`check11`=T2.`訪員確認上述量表是否完成7`,
T1.`sarcf_1`=T2.`走路穿越一個房間會困難嗎`,
T1.`sarcf_2`=T2.`您拿45公斤的物品是否感到困難`,
T1.`sarcf_3`=T2.`是否因為疾病或其他健康因素您從床上或椅子上站起來或坐下有困難`,
T1.`sarcf_4`=T2.`您能在沒有任何幫助的情況下獨立且不休息地連續爬10個台階嗎`,
T1.`sarcf_5`=T2.`過去一年中您跌倒過幾次`,
T1.`check12`=T2.`訪員確認上述量表是否完成8`,
T1.`past1_drink`=T2.`您曾經喝過酒包含藥酒補酒嗎`,
T1.`d2_drinks`=T2.`有幾歲開始喝酒`,
T1.`drink_k1`=T2.`您常喝哪一種酒啤酒`,
T1.`drink_k2`=T2.`您常喝哪一種酒中國酒`,
T1.`drink_k3`=T2.`您常喝哪一種酒烈酒`,
T1.`drink_k4`=T2.`您常喝哪一種酒水果酒`,
T1.`drink_k5`=T2.`您常喝哪一種酒補藥酒`,
T1.`drink_k6`=T2.`您常喝哪一種酒米酒`,
T1.`drink_k7`=T2.`您常喝哪一種酒其他`,
T1.`drink_k7_o`=T2.`其他酒`,
T1.`drink_t`=T2.`您喝酒喝幾年從第一次喝酒到最後一次喝酒`,
T1.`drink_q`=T2.`您是否曾戒過酒超過6個月未喝酒`,
T1.`drink_qt1`=T2.`已戒酒幾年未再喝`,
T1.`drink_qt2`=T2.`戒過幾年現在又喝`,
T1.`drink_red`=T2.`喝酒之後會不會臉紅`,
T1.`B_1_1`=T2.`你多久喝一次酒`,
T1.`B_1_2`=T2.`在一般喝酒的日子你一天可以喝多少酒精當量`,
T1.`B_1_3`=T2.`多久會有一次喝超過六酒精當量的酒`,
T1.`B_1_4`=T2.`過去一年中你發現一旦開始喝第一口酒後就會一直喝下去的情況有多常見`,
T1.`B_1_5`=T2.`過去一年中因為喝酒而無法做你平常該做的事的情形有多常見`,
T1.`B_1_6`=T2.`過去一年中經過一段時間的大量飲酒後早上需要喝一杯才會覺得舒服的情形有多常見`,
T1.`B_1_7`=T2.`過去一年中在酒後覺得愧疚或自責的情形有多常見`,
T1.`B_1_8`=T2.`過去一年中酒後忘記前一晚發生事情的情況有多常見`,
T1.`B_1_9`=T2.`是否曾經有其他人或是你自己因為你的喝酒而受傷過`,
T1.`B_1_10`=T2.`是否曾有親友醫生或其他醫事人員關心你喝酒的問題或是建議你少喝點`,
T1.`check13`=T2.`訪員確認上述量表是否完成9`;